FROM arm32v7/python:3.6-slim-stretch

MAINTAINER <pjialin admin@pjialin.com>
ENV TZ Asia/Shanghai

WORKDIR /code

COPY ./sources.list /etc/apt/
RUN apt-get update && apt-get install -y --allow-unauthenticated gcc libxml2-dev libxslt-dev libz-dev python-dev
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


RUN mkdir -p /data/query /data/user
VOLUME /data

COPY . .

COPY env.docker.py.example /config/env.py

CMD [ "python", "main.py" , "-c", "/config/env.py"]
